package com.oneinc.lambda.utils;

import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent;
import com.google.gson.Gson;
import com.oneinc.lambda.models.DTO.RestDataDTO;
import lombok.experimental.UtilityClass;

import java.util.HashMap;

/**
 * Utilities to process input and output parameters for Lambda.
 *
 * @author oklimenko@gmail.com
 */
@UtilityClass
public class RequestResponseUtils {

    private static String method = "CreatePaymentMaster"; // TODO - extract from body
    private static String restData = "{\"str_json\": \"{          \\\"PM_CarrierId\\\" :\\\"{{PM_CarrierId}}\\\",         \\\"PM_PaymentID\\\":\\\"PMT123233222332232\\\",         \\\"PM_PaymentType\\\":\\\"Contact(s)\\\",         \\\"PM_Amount\\\":\\\"127.12\\\",         \\\"PM_UserId\\\":\\\"user01\\\",         \\\"PM_User_FirstName\\\":\\\"John\\\",         \\\"PM_User_LastName\\\":\\\"R\\\",         \\\"PM_User_EmailAddress\\\":\\\"mmiscioscia@email.lynn.edu\\\",         \\\"CL_ClaimNumber\\\": \\\"052017\\\",         \\\"PCON_ContactId\\\": \\\"PCON121503\\\",         \\\"PCON_FirstName\\\": \\\"Joe\\\",         \\\"PCON_LastName\\\": \\\"Root\\\",     \\\"PMA_Street\\\": \\\"09-5A, Woodland Hills\\\",         \\\"PMA_City\\\": \\\"Simi Valley\\\",         \\\"PMA_State\\\": \\\"CA\\\",         \\\"PMA_Zipcode\\\": \\\"93065-2234\\\",         \\\"PMA_Country\\\": \\\"USA\\\",         \\\"PMETHOD\\\": \\\"Check\\\",         \\\"PMA_MailTo\\\": \\\"James Smith\\\",         \\\"PM_Additional_Text_3\\\": \\\"James Smith\\\"      }\" }";

    public String getParameterFromBody(APIGatewayProxyRequestEvent event, String parameterName) {
        //        return event.getQueryStringParameters(parameterName);
        // TODO exctract parameters from BODY correctly
        if ("method".equals(parameterName)) {
            return method;
        }
        return restData;
    }

    public APIGatewayProxyResponseEvent generateSuccessJsonResponse(String responseBody) {
        APIGatewayProxyResponseEvent response = new APIGatewayProxyResponseEvent();
        response.setIsBase64Encoded(true);
        response.setStatusCode(200);
        HashMap<String, String> headers = new HashMap<>();
        headers.put("Content-Type", "application/json");
        response.setHeaders(headers);
        response.setBody(responseBody);
        return response;
    }

    private APIGatewayProxyResponseEvent generateTestHtmlResponse() {
        APIGatewayProxyResponseEvent response = new APIGatewayProxyResponseEvent();
        response.setIsBase64Encoded(false);
        response.setStatusCode(200);
        HashMap<String, String> headers = new HashMap<String, String>();
        headers.put("Content-Type", "text/html");
        response.setHeaders(headers);
        response.setBody("<!DOCTYPE html><html><head><title>AWS Lambda sample</title></head><body>" +
                "<h1>Welcome</h1><p>Page generated by a Lambda function.</p>" +
                "</body></html>");
        return response;
    }

    public String extractRestData(Gson gson, String wrappedRestData) {
        RestDataDTO restDataDTO = gson.fromJson(wrappedRestData, RestDataDTO.class);
        return restDataDTO.getStr_json();
    }
}
